### ISSUE TITLE
Broken lerp

### ISSUE THREAD

**Issue by diogovtx** [redorav/hlslpp#21]
Lerp seems to be broken. Had to revert to path marked as slower in _hlslpp_lerp_ps in order to get it working.

**Comment by redorav** [comment]
Hi @diogovtx,

Thanks for reporting. You are 100% correct that it is wrong, I was using msub instead of subm. This is what happens when you don't have enough unit tests :)

I have realized that there are actually precision implications from using one over the other. I have checked with fxc and the version I had tagged as slower is actually more correct. Since the second one was just marginally slower I'll go with the one most aligned with fxc. I have now added unit tests as well to this case.

Fixed via 8cd480b50c8740ad5a9b395a7bb7f5801979c000
