### ISSUE TITLE
Integer vectors do not define /= operator

### ISSUE THREAD

**Issue by egorodet** [redorav/hlslpp#45]
Floating point vector types have /= operator, but integer vectors do not.

**Comment by redorav** [comment]
This is a tricky one. Integer division is not well supported at all in SIMD. I'll give it some thought and see what I can come up with (unless of course you want to give it a shot)

**Comment by redorav** [comment]
Actually, I can implement the operator just fine. The problem lies in the _hlslpp_div_epi32 implementation, which at the moment simply casts to float, divides, and casts back. It's clearly wrong and needs a better "software" implementation, since as far as I know there are no instructions that implement integer divide in SSE. I could be mistaken. NEON does appear to support it.

**Comment by redorav** [comment]
Close via e391137faee2311bc3646717359862d0578064ad
