### ISSUE TITLE
uint1/2/3/4 store/load

### ISSUE THREAD

**Issue by plekakis** [redorav/hlslpp#56]
Currently there's no store/load for uint types, is this planned on being implemented?

**Comment by redorav** [comment]
Hi Akis, thanks for the message. There's no particular reason those aren't implemented and it would take no time to do.

I'm taking care of family matters at the moment and I don't know when I'll be able to look at it. If you're feeling brave you could submit a PR, otherwise you could make it work locally and update later.

**Comment by plekakis** [comment]
Thanks for replying, I am also very busy and unlikely to be able to look into this.
I will wait, as it's not urgent at this moment :)

**Comment by redorav** [comment]
Fixed via d46dbf208b2701e92f59dc85dbb907aabd874cf6
