### ISSUE TITLE
* operator brake mult function in quaternion

### ISSUE THREAD

**Issue by Tormund** [redorav/hlslpp#67]
Hello I found weird issue, this example compiles:
```
    auto r = hlslpp::mul(hlslpp::quaternion{0.0, 0.0, 0.0, 0.0}, hlslpp::quaternion{0.0, 0.0, 0.0, 0.0});
    auto r2 = hlslpp::mul(hlslpp::quaternion{0.0, 0.0, 0.0, 0.0}, hlslpp::float3{0.0, 0.0, 0.0});
```

but this is not:
```
    auto r = hlslpp::quaternion{0.0, 0.0, 0.0, 0.0} * hlslpp::quaternion{0.0, 0.0, 0.0, 0.0};
    auto r2 = hlslpp::mul(hlslpp::quaternion{0.0, 0.0, 0.0, 0.0}, hlslpp::float3{0.0, 0.0, 0.0});
 ```
with next error - `namespace "hlslpp" has no member "mul"`

Windows 11, gcc 11.1.0

**Comment by redorav** [comment]
Hi @Tormund, thanks for your message. In your example the line that goes wrong is

`auto r = hlslpp::quaternion{0.0, 0.0, 0.0, 0.0} * hlslpp::quaternion{0.0, 0.0, 0.0, 0.0};`

because there is no * operator that takes two quaternions. HLSL defines the * operator as component-wise multiplication which doesn't make a lot of sense for quaternions. The only multiplication operators that exist are accessible through the mul() function.

mul(quaternion, quaternion) multiplies two quaternions together

mul(quaternion, float3) rotates a vector using a quaternion

mul(float3, quaternion) rotates a vector using the inverse of the quaternion (effectively the opposite rotation)

Other than that there are no other multiplication operations. Does that clarify things a bit?

**Comment by Tormund** [comment]
@redorav Thanks. After getting a compilation error, I understood my mistake. This is my first time using this library, and I didn't know that there is no * operator for quaternions. It would be great if incorrect code would not compile. Anyway, thank you for the advice.

**Comment by redorav** [comment]
Hi @Tormund, I'm glad you found a solution. I'm not sure I understand what you mean when you say

`It would be great if incorrect code would not compile (using operator * for quaternions)`

The bug is about this code not compiling isn't it? I put the operator * in MSVC and it fails to compile. Can you post all the error messages you get?

**Comment by Tormund** [comment]
@redorav Sorry, everything is okay. It doesn't compile. It's my mistake. I was running many tests with another 4 math libraries and hlslpp in the same project, and I got confused. Thank you for your help!

**Comment by redorav** [comment]
@Tormund glad you are getting good value out of the library. Let me know if there are any other issues. When you say hlslpp outperforms other libraries, do you have any numbers and a specific test? I've been wanting to write performance tests for a while now but haven't really got to it

**Comment by Tormund** [comment]
@redorav, I ran several tests for each library. For vectors, I tested addition, normalization, dot product, cross product, and scalar multiplication. For quaternions, I tested multiplication, conjugation, and multiplication by a vector. For matrices, I tested multiplication and inversion. Each test was run in a loop with ten million iterations using randomly generated values that were passed to each test in the same order. All the information was gathered using an RAII object that calculated its lifetime and outputted the results in microseconds. At this point, I'm not entirely sure if I'm using all the libraries properly, but it seems that hlslpp performs similarly to cglm.

Here is result with Ofast flag:
Done - hlslpp_vectors in: 75216
Done - hlslpp_quaternions in: 69075
Done - hlslpp_matrixes in: 92163
Done - HLSLPP in: 239461

Done - cglm_vectors in: 72785
Done - cglm_quaternions in: 65330
Done - cglm_matrixes in: 89840
Done - CGLM in: 230156

And with O3:
Done - hlslpp_vectors in: 72621
Done - hlslpp_quaternions in: 68794
Done - hlslpp_matrixes in: 86990
Done - HLSLPP in: 231015

Done - cglm_vectors in: 91020
Done - cglm_quaternions in: 58385
Done - cglm_matrixes in: 99146
Done - CGLM in: 251470

**Comment by redorav** [comment]
@Tormund Thank you for that, most useful to have some ballpark numbers. If you end up using hlslpp and care about performance improvements in some area you suspect is slower than it should be (I'm seeing that quaternions are slower than in cglm) let me know and we can accommodate the changes that you need.
