### ISSUE TITLE
Some vector double functions missing

### ISSUE THREAD

**Issue by apple-phi** [redorav/hlslpp#76]
Hiya, I've noticed that double precision vectors seem to be missing a few functions that I'd assumed were intended for all vector precisions, e.g. cross products, normalisation, cosh. I think there's a few more but I haven't done an extended search. I'd initially assumed that float vectors and double vectors would have the same interface.

If this behaviour is intended, please would you be able to document which functions are restricted to only float vectors? Or if it's not intended, please would you be able to give a brief summary of SIMD implementations for them so I can try and use double precision vectors in my code?

**Comment by redorav** [comment]
Hi @apple-phi it's just an omission really, not by design. I use double vectors less often than I do float vectors and I've dedicated less attention to them. They are meant to have the same interface, I just haven't had the time and people don't seem to be that interested in them either.

The complexity with double is that they have two implementations, one before AVX and the other with AVX. It takes time to implement and verify them. I can see that there are several basic functions that haven't been implemented yet as you say. Reference implementations for them can be found in hlsl++_vector_float, for example

```cpp
inline n128 _hlslpp_sin_ps(n128 x)
{
	static const n128 sin_c1 = f4_1;
	static const n128 sin_c3 = _hlslpp_set1_ps(-1.6665578e-1f);
	static const n128 sin_c5 = _hlslpp_set1_ps(8.3109378e-3f);
	static const n128 sin_c7 = _hlslpp_set1_ps(-1.84477486e-4f);

	// Range reduction (into [-pi, pi] range)
	// Formula is x = x - round(x / 2pi) * 2pi

	x = _hlslpp_subm_ps(x, _hlslpp_round_ps(_hlslpp_mul_ps(x, f4_inv2pi)), f4_2pi);

	n128 gtpi2 = _hlslpp_cmpgt_ps(x, f4_pi2);
	n128 ltminusPi2 = _hlslpp_cmplt_ps(x, f4_minusPi2);

	n128 ox = x;

	// Use identities/mirroring to remap into the range of the minimax polynomial
	x = _hlslpp_sel_ps(x, _hlslpp_sub_ps(f4_pi, ox), gtpi2);
	x = _hlslpp_sel_ps(x, _hlslpp_sub_ps(f4_minusPi, ox), ltminusPi2);

	n128 x2 = _hlslpp_mul_ps(x, x);
	n128 result;
	result = _hlslpp_madd_ps(x2, sin_c7, sin_c5);
	result = _hlslpp_madd_ps(x2, result, sin_c3);
	result = _hlslpp_madd_ps(x2, result, sin_c1);
	result = _hlslpp_mul_ps(result, x);
	return result;
}
```
That can work as a starting point. If there's further interest and this would be useful to you, I can start slowly implementing and adding some of these to the double class.

**Comment by apple-phi** [comment]
@redorav Thanks for the reply! I'm pretty sure the only ones I'm missing that I need for my project is a cross product and normalisation. I'll probably just use a naive non-SIMD self-implementation for now but it would be great if you could add those into the library when you get the chance :)

**Comment by redorav** [comment]
@apple-phi I added normalization as it was simple to do, I'll see if I can find the time to add the cross product soon

**Comment by apple-phi** [comment]
@redorav Amazing, thank you! Lmk if you get round to doing the cross product :)

**Comment by redorav** [comment]
Implemented in https://github.com/redorav/hlslpp/commit/24c316878834c8a24ba9baf1845f463b365eb765
